dbgapi/win32: No windef.h in amd-dbgapi.h.in
[amd-dbgapi] In file included from D:/therock/src/rocm-systems/projects/rocdbgapi/src/logging.cpp:21:
[amd-dbgapi] In file included from D:/therock/src/rocm-systems/projects/rocdbgapi/src\logging.h:24:
[amd-dbgapi] In file included from D:/therock/build/debug-tools/amd-dbgapi/build/include/amd-dbgapi\amd-dbgapi.h:546:
[amd-dbgapi] In file included from C:\Program Files (x86)\Windows Kits\10\\include\10.0.26100.0\\shared\windef.h:24:
[amd-dbgapi] In file included from C:\Program Files (x86)\Windows Kits\10\\include\10.0.26100.0\\shared\minwindef.h:182:
[amd-dbgapi] C:\Program Files (x86)\Windows Kits\10\\include\10.0.26100.0\\um\winnt.h:169:2: error: "No Target Architecture"
[amd-dbgapi]   169 | #error "No Target Architecture"
[amd-dbgapi]       |  ^
[amd-dbgapi] C:\Program Files (x86)\Windows Kits\10\\include\10.0.26100.0\\um\winnt.h:253:2: error: Must define a target architecture.
[amd-dbgapi]   253 | #error Must define a target architecture.
[amd-dbgapi]       |  ^

We are including windef.h instead of windows.h to minimize global
namespace polution.  We only need the include for HANDLE and DWORD,
which are simple typedefs.  So remove the header inclusion and define
our own versions of those.

Change-Id: I83348e1457d95452d3cad59b329bf9f4e57fc386
commit-id:e41ab5e4