Fix building dbgapi as a static library
Since 4bfddf5494 ("dbgapi/win32: __declspec(dllexport) instead of
--version-script"), building dbgapi as a static library on Windows
fails with errors such as:

 .../rocm-dbgapi/src/initialization.cpp:41:1: error: function 'amd_dbgapi_status_t amd_dbgapi_initialize(amd_dbgapi_callbacks_s*)' definition is marked dllimport
    41 | amd_dbgapi_initialize (struct amd_dbgapi_callbacks_s *callbacks)
       | ^~~~~~~~~~~~~~~~~~~~~

The symbols end up "marked dllimport" because with:

 set_target_properties(amd-dbgapi PROPERTIES
   ...
   DEFINE_SYMBOL "AMD_DBGAPI_EXPORTS"
   ...

... DEFINE_SYMBOL is a CMake convenience that only applies when (and
while) building a shared library.  When BUILD_SHARED_LIBS is OFF,
DEFINE_SYMBOL does nothing.  So AMD_DBGAPI_EXPORTS ends up not defined
in amd-dbgapi.h, which results in AMD_DBGAPI mapping to
AMD_DBGAPI_IMPORT, here, in amd-dbgapi.h.in:

  #define AMD_DBGAPI AMD_DBGAPI_IMPORT

AMD_DBGAPI_IMPORT in turn is unconditionally defined to
__declspec(dllimport) on Windows.

So there are two issues:

 - The dbgapi build itself is treated as importing symbols (as a
   consumer) instead of exporting them (as a producer).

 - The import/export decorations are applied even when dbgapi is built
   as a static library, where they should not be used at all.

Fix this by teaching amd-dbgapi.h about whether dbgapi was built as a
static or shared library.  Since the header is generated, define
AMD_DBGAPI_STATIC_LIB (0 or 1) at configure time and use it to skip
using import/export decorations.

This also ensures that clients, including those which do not use CMake
(e.g. GDB), automatically see consistent definitions without needing
to know how dbgapi was built.

Change-Id: I31c8c947791551cc4e20218826561c1d242f298d
commit-id:12deacf2
(cherry picked from commit b1ac485c994985b67f1dd712693c81b614d0bf12)