Avoid dereferencing past the end iterator in memory_cache_t::write_back
I recently created a build using -D_GLIBCXX_DEBUG which showed me a
number of error when used by rocgdb:

    /usr/include/c++/9/debug/safe_iterator.h:307:
    In function:
        __gnu_debug::_Safe_iterator<_Iterator, _Sequence, _Category>::pointer
        __gnu_debug::_Safe_iterator<_Iterator, _Sequence,
        _Category>::operator->() const [with _Iterator =
        std::_Rb_tree_iterator<std::pair<const long unsigned int,
        amd::dbgapi::memory_cache_t::cache_line_t> >; _Sequence =
        std::__debug::map<long unsigned int,
        amd::dbgapi::memory_cache_t::cache_line_t>; _Category =
        std::forward_iterator_tag; __gnu_debug::_Safe_iterator<_Iterator,
        _Sequence, _Category>::pointer = std::pair<const long unsigned int,
        amd::dbgapi::memory_cache_t::cache_line_t>*]

    Error: attempt to dereference a past-the-end iterator.

    Objects involved in the operation:
        iterator "this" @ 0x0x7ffdc4542f80 {
          state = past-the-end;
          references sequence @ 0x0x61b0000196b0
        }

    Fatal signal: Aborted
    ----- Backtrace -----
    0x55a55fc43d46 gdb_internal_backtrace_1
            ../../gdb/bt-utils.c:122
    0x55a55fc43f53 _Z22gdb_internal_backtracev
            ../../gdb/bt-utils.c:168
    0x55a56029bbd1 handle_fatal_signal
            ../../gdb/event-top.c:946
    0x7f0378b7608f ???
            /build/glibc-SzIz7B/glibc-2.31/signal/../sysdeps/unix/sysv/linux/x86_64/sigaction.c:0
    0x7f0378b7600b __GI_raise
            ../sysdeps/unix/sysv/linux/raise.c:51
    0x7f0378b55858 __GI_abort
            /build/glibc-SzIz7B/glibc-2.31/stdlib/abort.c:79
    0x7f0378de3108 ???
    0x7f0379341763 _ZNK11__gnu_debug14_Safe_iteratorISt17_Rb_tree_iteratorISt4pairIKmN3amd6dbgapi14memory_cache_t12cache_line_tEEENSt7__debug3mapImS7_St4lessImESaIS8_EEESt20forward_iterator_tagEptEv
            /usr/include/c++/9/debug/safe_iterator.h:307
    0x7f0379315058 _ZN3amd6dbgapi14memory_cache_t10write_backEmm
            /home/lancesix/src/worktrees/rocgdb/dbgapi-mem-access/rocm-dbgapi/src/memory.cpp:575
    0x7f03794cd505 _ZN3amd6dbgapi6detail11aql_queue_t19queue_state_changedEv
            /home/lancesix/src/worktrees/rocgdb/dbgapi-mem-access/rocm-dbgapi/src/queue.cpp:518
    [...]

This is because of we end up dereferencing an iterator past the end of
the container.

This patch adds a check that the iterator has not reached the end of the
search range before dereferencing it.

Change-Id: I882f31ad0cd01dffaaf3b6659e11b86b50406a7d