rocdbgapi: define instruction_t after architecture_t MIME-Version: 1.0 Content-Type: text/plain; charset=UTF-8 Content-Transfer-Encoding: 8bit
GCC 16 has -Wsfinae-incomplete enabled by default, which breaks the build
with -Werror:

    [  4%] Building CXX object CMakeFiles/amd-dbgapi.dir/src/agent.cpp.o
    In file included from /home/simark/src/rocm-systems/projects/rocdbgapi/src/agent.cpp:22:
    /home/simark/src/rocm-systems/projects/rocdbgapi/src/architecture.h:133:7: error: defining ‘amd::dbgapi::architecture_t’, which previously failed to be complete in a SFINAE context [-Werror=sfinae-incomplete=]
      133 | class architecture_t : private utils::not_copyable_t
          |       ^~~~~~~~~~~~~~

Compiling with -Wsfinae-incomplete=2 and -Wsystem-headers reveals the root
of the problem:

    In file included from /usr/include/c++/16/functional:74:
    /usr/include/c++/16/bits/refwrap.h: In substitution of ‘template<class _Functor> struct std::_Maybe_get_result_type<_Functor, std::__void_t<typename _Functor::result_type> > [with _Functor = amd::dbgapi::architecture_t]’:
    /usr/include/c++/16/bits/refwrap.h:137:12:   required from ‘struct std::_Weak_result_type_impl<amd::dbgapi::architecture_t>’
      137 |     struct _Weak_result_type_impl
          |            ^~~~~~~~~~~~~~~~~~~~~~
    /usr/include/c++/16/bits/refwrap.h:166:12:   required from ‘struct std::_Weak_result_type_memfun<amd::dbgapi::architecture_t, false>’
      166 |     struct _Weak_result_type_memfun
          |            ^~~~~~~~~~~~~~~~~~~~~~~~
    /usr/include/c++/16/bits/refwrap.h:187:12:   required from ‘struct std::_Weak_result_type<amd::dbgapi::architecture_t>’
      187 |     struct _Weak_result_type
          |            ^~~~~~~~~~~~~~~~~
    /usr/include/c++/16/bits/refwrap.h:227:12:   required from ‘struct std::_Reference_wrapper_base<amd::dbgapi::architecture_t>’
      227 |     struct _Reference_wrapper_base
          |            ^~~~~~~~~~~~~~~~~~~~~~~
    /usr/include/c++/16/bits/refwrap.h:290:12:   required from ‘struct std::_Reference_wrapper_base_memfun<amd::dbgapi::architecture_t, false>’
      290 |     struct _Reference_wrapper_base_memfun
          |            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    /usr/include/c++/16/bits/refwrap.h:310:11:   required from ‘class std::reference_wrapper<const amd::dbgapi::architecture_t>’
      310 |     class reference_wrapper
          |           ^~~~~~~~~~~~~~~~~
    /home/simark/src/rocm-systems/projects/rocdbgapi/src/architecture.h:87:48:   required from here
       87 |   std::reference_wrapper<const architecture_t> m_architecture;
          |                                                ^~~~~~~~~~~~~~
    /usr/include/c++/16/bits/refwrap.h:137:12: error: failed to complete ‘amd::dbgapi::architecture_t’ in SFINAE context [-Werror=sfinae-incomplete=]
      137 |     struct _Weak_result_type_impl
          |            ^~~~~~~~~~~~~~~~~~~~~~

In "architecture.h", `instruction_t` is defined before `architecture_t`,
but holds a:

    std::reference_wrapper<const architecture_t> m_architecture;

std::reference_wrapper uses SFINAE for some reason on the inner type, and
for this the type should be defined at this point.  Move `instruction_t`
below `architecture_t` to make that happen.

An alternative would be to change `m_architecture` to be a pointer.
[rocm-systems] ROCm/rocm-systems#11254 (commit a18cfc6)