Fix a build error
architecture.cpp: In member function 'virtual uint64_t amd::dbgapi::gfx9_base_t::wave_get_info():
architecture.cpp:1711:1: error: control reaches end of non-void function [-Werror=return-type]
 }

The dbgapi_assert does not prevent control to reach the end of the
function when compiled in Release mode.  Replaced with an error()
which does.

Change-Id: Ia59d048d3876d8a43ef694d433f236f916ae018e