dbgapi: Handle function pointers explicitly in to_string
Compiling dbgapi with clang++ targeting x86_64-pc-windows-msvc fails
with the following warning (turned into error):

 .../rocdbgapi/src\logging.h:83:9: error: implicit conversion between pointer-to-function and pointer-to-object is a Microsoft extension [-Werror,-Wmicrosoft-cast]
    83 |   ss << v;
       |         ^

That's in the to_string template function.  An example of a function
pointer getting there comes from amd_dbgapi_disassemble_instruction,
which passes its 'symbolizer' argument to TRACE_BEGIN.  'symbolizer'
is a function pointer.

Note: Converting function pointer to data pointer in ISO C++ is
conditionally-supported, i.e., implementation-defined:
  https://eel.is/c++draft/expr.compound#expr.reinterpret.cast-8

It is necessarily valid POSIX, as dlsym returns void *, and also valid
on WIN32 as an extension.  In any case, we were already assuming that
works, just implicitly.

Change-Id: Ida71fe78bf3dc9efacf196b7c0363aeacabc4626
commit-id:579926d6